{% set name = "python-designateclient" %}
{% set version = "6.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-designateclient-{{ version }}.tar.gz
  sha256: 1adc2a074b30d842cf9787f53310c37949195bf4e34da3984e5635b7b8a4689c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.8
    - setuptools
  run:
    - cliff !=2.9.0,>=2.8.0
    - debtcollector >=1.2.0
    - jsonschema >=3.2.0
    - keystoneauth1 >=3.4.0
    - osc-lib >=1.8.0
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - python >=3.8
    - requests >=2.14.2
    - stevedore >=1.20.0

test:
  imports:
    - designateclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/python-designateclient/latest
  summary: OpenStack DNS-as-a-Service - Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
